---
- hosts: appserver
  become: yes
  tasks: 
  - name: update package
    apt:
      update_cache: true
  - name: install apache
    apt:
      name: apache2
      state: present
  - name: copy content to webserver
    copy:
    dest: /var/www/html/index.html
    content: hi ajay 
  - name: restart apache2
    service: 
      name: apache2
      state: restarted 
   
