---
- hosts: appserver
  become: yes
  tasks:
  - name: update packages
    apt:
      update_cache: yes
  - name: install apache2
    apt:
      name: apache2
      state: present
    notify:
    - restart apache2
  - name: webpage creation
    copy:
      dest: /var/www/html/index.html
      content: hai hello 
    notify:
    - restart apache2
  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted